### PR TITLE
aws-alias.sh: strip quotes from returned instance id and IP address

### PR DESCRIPTION
**Pull request by msgrasser**
aws-ip currently stores the IP in quotes to $instanceIp, which messes up aws-ssh. I've trimmed the quotes prior to storing in $instanceIp

### CODE REVIEW

**Comment by jpuderer** [comment]
I noticed this too.  The problem is happening because your AWS CLI output type is JSON.

Another solution is to add "--output text" to the aws commands.

**Comment by msgrasser** [comment]
Yes, that is certainly another solution that I came across just after
submitting these PRs. However, this implementation doesn't hurt the folks
who forgot that flag, and helps those who did. So I think it's still worth
incorporating.

**Comment by racheltho** [comment]
Our setup guide says to use text output mode in aws configure.  We'd prefer if someone forgot to do this that they found out sooner (otherwise, we think this would cause issues for them later on).

**Comment by msgrasser** [comment]
Fair enough, thanks for the explanation!

**Pull request closed without merging**
