### PR TITLE
CPU setup

### PR DESCRIPTION
**Pull request by psave**
Got the folder structure working for the CPU setup. Am able to run both dogscats as well as dogs_cats_redux.

### CODE REVIEW

**Comment by psave** [comment]
Got the folder structure working for the CPU setup. Am able to run both dogscats as well as dogs_cats_redux.

**Comment by psave** [comment]
Got the folder structure working for the CPU setup. Am able to run both dogscats as well as dogs_cats_redux.

**Comment by jph00** [comment]
Not sure what's going on with this PR but it seems to be deleting a bunch of important files... Please submit a minimal PR with a clear explanation of the changes and reasoning behind each one.

**Comment by psave** [comment]
Hi Jeremy, 

Sorry about the poor commit earlier.  On a slightly related note, I am working with a group of people in Vancouver, Canada who are following your Fast.Ai course. I am wondering if you would be interested to attend a session for 15-30 minutes to field questions? There are about 20 of us that are working through the material. The format of our meetup is the following:
- We meet every two weeks
- Every Meetup covers 1 lecture of Fast.Ai
- Everyone is meant to review the material and complete the exercises
- Each Meetup someone volunteers to present the main topics covered for further discussion
- Some time is saved at the end of the meetup for coding

Boeing Labs has kindly allowed for us to hold our meetings at their office and I am sure that everyone would be extremely excited if you could field some questions. Would you happen to be available on Thursday, October 12th for 15-30 minutes? Our session starts at 6:30pm PST and ends 8pm. Anytime between then would be great. I happy to ask our group for questions in advance as well if that helps.

Here is a link to our meetup: https://www.meetup.com/LearnDataScience/events/241882142/ . It is actually a sub-group of our "Learn data science by doing Kaggle competitions" meetup: https://www.meetup.com/LearnDataScience/

I am also happy to chat via LinkedIn as this may not be the forum for a discussion. (https://www.linkedin.com/in/paulsave/)

Thanks,

Paul

**Pull request closed without merging**
