### PR TITLE
Add Jupyter notebook server init and runner script for AWS

### PR DESCRIPTION
**Pull request by inancgumus**
Hi,

I spent some time to be able to run Jupyter notebooks on AWS.

To do that, 

- I added a script that initializes a Jupyter notebook server (`init.sh`) and,
- A script to run Jupyter notebook server (`run.sh`)

### CODE REVIEW

**Comment by racheltho** [comment]
This looks good.  Can you add documentation for the user?  In particular, let the user know this will add an open ssl certificate that they'll need to use whenever starting their notebook

**Comment by inancgumus** [comment]
@racheltho Oh sorry, I missed that one. What do you think about where should I add the documentation? Thanks!

**Comment by jph00** [comment]
Just adding as comments to the top of the scripts should be fine. Also please remove the .swp file that you accidentally committed. (PS you may want to do this http://stackoverflow.com/questions/1636297/how-to-change-the-folder-path-for-swp-files-in-vim )

**Comment by inancgumus** [comment]
@racheltho @jph00 Thanks for the comments. I added some documentation.

**Pull request merged**
